import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {routeFeatures,withOfficialWater,ordered,routeCard,text,safeURL,photoURL,photoHTML} from '../public/field-guide/guide.js';
const main=JSON.parse(fs.readFileSync('public/field-guide/main.json')),full=JSON.parse(fs.readFileSync('public/field-guide/full.json')),water=JSON.parse(fs.readFileSync('public/sideways/actv-water-paths.json'));
test('two primary routes retain their 11/28 stops, eight translations and five prompts',()=>{for(const [route,n] of [[main,11],[full,28]]){assert.equal(ordered(route).length,n);for(const v of route.visits){assert.equal(v.ideas.length,5);assert.equal(v.copy.length,8);for(const i of v.ideas)assert.equal(i.copy.length,8);}}});
test('only requested route geometry is returned and missing paths never become straight lines',()=>{assert.equal(routeFeatures(full).features.some(f=>f.properties.boat),false);const boats=routeFeatures(main).features.filter(f=>f.properties.boat);assert.deepEqual(boats.map(f=>f.properties.line),['1','5.2']);assert.notEqual(boats[0].properties.color,boats[1].properties.color);assert.ok(boats.every(f=>f.geometry.coordinates.length>20));const r=structuredClone(main);r.segments.forEach(s=>{s.geometry=[];delete s.officialLegs});assert.equal(routeFeatures(r).features.length,0);});
test('official legacy water paths are immutable and are not applied to moved piers',()=>{const r=structuredClone(main),s=r.segments.find(s=>s.type==='vaporetto');delete s.officialLegs;s.geometry=[];const before=JSON.stringify(r);assert.equal(withOfficialWater(r,water).segments.find(s=>s.type==='vaporetto').officialLegs.length,2);assert.equal(JSON.stringify(r),before);s.transitStops[0].longitude+=.01;assert.equal(withOfficialWater(r,water).segments.find(s=>s.type==='vaporetto').officialLegs,undefined);});
test('visitor cards escape draft text and reject script links',()=>{const r=structuredClone(main);r.copy[0].title='<img onerror=alert(1)>';const html=routeCard(r,'en');assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<img onerror'));assert.equal(safeURL('javascript:alert(1)'),'');assert.equal(text('<b>'),'&lt;b&gt;');});

test('unsaved photo previews reject private endpoints and token URLs before save',()=>{for(const url of ['https://erenedebali.com/api/photos/1','https://erenedebali.com/image/1/web?preview=1','https://erenedebali.com/image/1/web?token=secret','https://elsewhere.example/photo.jpg']) {assert.equal(photoURL(url),''); assert.equal(photoHTML({url}), '');} assert.equal(photoURL('https://erenedebali.com/photo-image/12/web?v=2'),'https://erenedebali.com/photo-image/12/web?v=2');});
