import test from 'node:test';import assert from 'node:assert/strict';import {createServer} from '../server.mjs';
let server,base;
test.before(async()=>{server=await createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
test.after(()=>new Promise(r=>server.close(r)));
test('root is independently branded and allows own-origin location',async()=>{const r=await fetch(base);assert.equal(r.status,200);assert.match(await r.text(),/<h1 data-no-translate="">Venice Sideways<\/h1>/);assert.match(r.headers.get('permissions-policy'),/geolocation=\(self\)/);assert.equal(r.headers.get('x-frame-options'),'DENY');});
test('old path alias redirects without overriding fragment or query',async()=>{const r=await fetch(base+'/venice-photography-walk-map?lang=tr',{redirect:'manual'});assert.equal(r.status,308);assert.equal(r.headers.get('location'),'/?lang=tr');});
test('private application paths and location uploads are absent',async()=>{for(const p of ['/admin','/.env','/server.mjs','/analytics/collect','/api/location','/%2e%2e/server.mjs'])assert.equal((await fetch(base+p)).status,404,p);assert.equal((await fetch(base+'/api/location',{method:'POST',body:'never-record-this'})).status,405);});
test('static assets have correct MIME, caching and no gallery runtime',async()=>{const r=await fetch(base+'/walk-map-v5.js');assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/javascript/);const body=await r.text();assert.ok(body.includes('https://venicesideways.com/'));assert.ok(!body.includes('https://erenedebali.com/venice-photography-walk-map'));const cached=await fetch(base+'/walk-map-v5.js',{headers:{'If-None-Match':r.headers.get('etag')}});assert.equal(cached.status,304);});
test('healthcheck works',async()=>{assert.equal(await (await fetch(base+'/healthz')).text(),'ok');});
